replicaCount: 2

image:
  repository: 975050024946.dkr.ecr.us-west-1.amazonaws.com/profile-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 3002

serviceAccount:
  create: false

env:
  - name: MONGO_URL
    value: "mongodb+srv://reshma:reshma@cluster0.tgvel.mongodb.net/tm"
