apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: 975050024946.dkr.ecr.us-west-1.amazonaws.com/profile-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URL
          value: "mongodb+srv://reshma:reshma@cluster0.tgvel.mongodb.net/tm"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP  # Service is internal
