replicaCount: 2

image:
  repository: 975050024946.dkr.ecr.us-west-1.amazonaws.com/frontend-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 80


