apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
